export default {
    GET_PRIMARY_CATEGORY_REQUEST: "GET_PRIMARY_CATEGORY_REQUEST",
    GET_PRIMARY_CATEGORY_SUCCESS: "GET_PRIMARY_CATEGORY_SUCCESS",
    GET_PRIMARY_CATEGORY_FAILURE: "GET_PRIMARY_CATEGORY_FAILURE",

    GET_SUBCATEGORY_REQUEST: "GET_SUBCATEGORY_REQUEST",
    GET_SUBCATEGORY_SUCCESS: "GET_SUBCATEGORY_SUCCESS",
    GET_SUBCATEGORY_FAILURE: "GET_SUBCATEGORY_FAILURE",

    GET_INSURANCE_REQUEST: "GET_INSURANCE_REQUEST",
    GET_INSURANCE_SUCCESS: "GET_INSURANCE_SUCCESS",
    GET_INSURANCE_FAILURE: "GET_INSURANCE_FAILURE",

    CREATE_SERVICE_REQUEST: "CREATE_SERVICE_REQUEST",
    CREATE_SERVICE_SUCCESS: "CREATE_SERVICE_SUCCESS",
    CREATE_SERVICE_FAILURE: "CREATE_SERVICE_FAILURE",
}