export default {
    GET_PRIMARY_CATEGORY_REQUEST: "GET_PRIMARY_CATEGORY_REQUEST",
    GET_PRIMARY_CATEGORY_SUCCESS: "GET_PRIMARY_CATEGORY_SUCCESS",
    GET_PRIMARY_CATEGORY_FAILURE: "GET_PRIMARY_CATEGORY_FAILURE",

    GET_SUBCATEGORY_REQUEST: "GET_SUBCATEGORY_REQUEST",
    GET_SUBCATEGORY_SUCCESS: "GET_SUBCATEGORY_SUCCESS",
    GET_SUBCATEGORY_FAILURE: "GET_SUBCATEGORY_FAILURE",

    GET_INSURANCE_REQUEST: "GET_INSURANCE_REQUEST",
    GET_INSURANCE_SUCCESS: "GET_INSURANCE_SUCCESS",
    GET_INSURANCE_FAILURE: "GET_INSURANCE_FAILURE",

    CREATE_SERVICE_REQUEST: "CREATE_SERVICE_REQUEST",
    CREATE_SERVICE_SUCCESS: "CREATE_SERVICE_SUCCESS",
    CREATE_SERVICE_FAILURE: "CREATE_SERVICE_FAILURE",

    GET_SERVICE_REQUEST: "GET_SERVICE_REQUEST",
    GET_SERVICE_SUCCESS: "GET_SERVICE_SUCCESS",
    GET_SERVICE_FAILURE: "GET_SERVICE_FAILURE", 
    
    // Auth
    SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

    SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',

    GET_AUTH_REQUEST: 'GET_AUTH_REQUEST',
    GET_AUTH_SUCCESS: 'GET_AUTH_SUCCESS',
    GET_AUTH_FAILURE: 'GET_AUTH_FAILURE',
    

}