export default {
    CREATE_PRIMARY_CATEGORY_REQUEST: "CREATE_PRIMARY_CATEGORY_REQUEST",
    CREATE_PRIMARY_CATEGORY_SUCCESS: "CREATE_PRIMARY_CATEGORY_SUCCESS",
    CREATE_PRIMARY_CATEGORY_FAILURE: "CREATE_PRIMARY_CATEGORY_FAILURE",
    
    GET_PRIMARY_CATEGORY_REQUEST: "GET_PRIMARY_CATEGORY_REQUEST",
    GET_PRIMARY_CATEGORY_SUCCESS: "GET_PRIMARY_CATEGORY_SUCCESS",
    GET_PRIMARY_CATEGORY_FAILURE: "GET_PRIMARY_CATEGORY_FAILURE",

    UPDATE_PRIMARY_CATEGORY_REQUEST: "UPDATE_PRIMARY_CATEGORY_REQUEST",
    UPDATE_PRIMARY_CATEGORY_SUCCESS: "UPDATE_PRIMARY_CATEGORY_SUCCESS",
    UPDATE_PRIMARY_CATEGORY_FAILURE: "UPDATE_PRIMARY_CATEGORY_FAILURE",

    DELETE_PRIMARY_CATEGORY_REQUEST: "DELETE_PRIMARY_CATEGORY_REQUEST",
    DELETE_PRIMARY_CATEGORY_SUCCESS: "DELETE_PRIMARY_CATEGORY_SUCCESS",
    DELETE_PRIMARY_CATEGORY_FAILURE: "DELETE_PRIMARY_CATEGORY_FAILURE",

    CREATE_SUBCATEGORY_REQUEST: "CREATE_SUBCATEGORY_REQUEST",
    CREATE_SUBCATEGORY_SUCCESS: "CREATE_SUBCATEGORY_SUCCESS",
    CREATE_SUBCATEGORY_FAILURE: "CREATE_SUBCATEGORY_FAILURE",

    GET_SUBCATEGORY_REQUEST: "GET_SUBCATEGORY_REQUEST",
    GET_SUBCATEGORY_SUCCESS: "GET_SUBCATEGORY_SUCCESS",
    GET_SUBCATEGORY_FAILURE: "GET_SUBCATEGORY_FAILURE",

    UPDATE_SUBCATEGORY_REQUEST: "UPDATE_SUBCATEGORY_REQUEST",
    UPDATE_SUBCATEGORY_SUCCESS: "UPDATE_SUBCATEGORY_SUCCESS",
    UPDATE_SUBCATEGORY_FAILURE: "UPDATE_SUBCATEGORY_FAILURE",

    DELETE_SUBCATEGORY_REQUEST: "DELETE_SUBCATEGORY_REQUEST",
    DELETE_SUBCATEGORY_SUCCESS: "DELETE_SUBCATEGORY_SUCCESS",
    DELETE_SUBCATEGORY_FAILURE: "DELETE_SUBCATEGORY_FAILURE",

    CREATE_INSURANCE_REQUEST: "CREATE_INSURANCE_REQUEST",
    CREATE_INSURANCE_SUCCESS: "CREATE_INSURANCE_SUCCESS",
    CREATE_INSURANCE_FAILURE: "CREATE_INSURANCE_FAILURE",

    GET_INSURANCE_REQUEST: "GET_INSURANCE_REQUEST",
    GET_INSURANCE_SUCCESS: "GET_INSURANCE_SUCCESS",
    GET_INSURANCE_FAILURE: "GET_INSURANCE_FAILURE",

    UPDATE_INSURANCE_REQUEST: "UPDATE_INSURANCE_REQUEST",
    UPDATE_INSURANCE_SUCCESS: "UPDATE_INSURANCE_SUCCESS",
    UPDATE_INSURANCE_FAILURE: "UPDATE_INSURANCE_FAILURE",

    DELETE_INSURANCE_REQUEST: "DELETE_INSURANCE_REQUEST",
    DELETE_INSURANCE_SUCCESS: "DELETE_INSURANCE_SUCCESS",
    DELETE_INSURANCE_FAILURE: "DELETE_INSURANCE_FAILURE",

    CREATE_SERVICE_REQUEST: "CREATE_SERVICE_REQUEST",
    CREATE_SERVICE_SUCCESS: "CREATE_SERVICE_SUCCESS",
    CREATE_SERVICE_FAILURE: "CREATE_SERVICE_FAILURE",

    GET_SERVICE_REQUEST: "GET_SERVICE_REQUEST",
    GET_SERVICE_SUCCESS: "GET_SERVICE_SUCCESS",
    GET_SERVICE_FAILURE: "GET_SERVICE_FAILURE",

    EDIT_SERVICE_REQUEST: "EDIT_SERVICE_REQUEST",
    EDIT_SERVICE_SUCCESS: "EDIT_SERVICE_SUCCESS",
    EDIT_SERVICE_FAILURE: "EDIT_SERVICE_FAILURE", 

    DELETE_SERVICE_REQUEST: "DELETE_SERVICE_REQUEST",
    DELETE_SERVICE_SUCCESS: "DELETE_SERVICE_SUCCESS",
    DELETE_SERVICE_FAILURE: "DELETE_SERVICE_FAILURE",
    
    GET_REPORTED_ERROR_REQUEST: "GET_REPORTED_ERROR_REQUEST",
    GET_REPORTED_ERROR_SUCCESS: "GET_REPORTED_ERROR_SUCCESS",
    GET_REPORTED_ERROR_FAILURE: "GET_REPORTED_ERROR_FAILURE",

    DELETE_REPORTED_ERROR_REQUEST: "DELETE_REPORTED_ERROR_REQUEST",
    DELETE_REPORTED_ERROR_SUCCESS: "DELETE_REPORTED_ERROR_SUCCESS",
    DELETE_REPORTED_ERROR_FAILURE: "DELETE_REPORTED_ERROR_FAILURE",

    // Auth
    SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

    SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',

    GET_AUTH_REQUEST: 'GET_AUTH_REQUEST',
    GET_AUTH_SUCCESS: 'GET_AUTH_SUCCESS',
    GET_AUTH_FAILURE: 'GET_AUTH_FAILURE',


}